import {
  CREDENTIALS,
  EMPLOYMENT_TYPES,
  LOCATIONS,
  ROLE_TYPES,
  SHIFTS,
  SPECIALTIES,
  SUB_SPECIALTIES,
} from './taxonomy';
import type {
  Application,
  AuditEntry,
  Candidate,
  DemoState,
  Invoice,
  InterviewSlot,
  Job,
  Organisation,
  PayrollEmployee,
  PlatformUser,
  Recruiter,
  RiskFlag,
  Submission,
  Taxonomy,
} from './types';

/**
 * Seed data for the demo.
 *
 * Deliberately varied: the jobs and candidates are built so the fit rules produce a
 * visible spread — an O&G consultant who was primary on 240 caesareans scores very
 * differently from one who has only assisted, and a cardiologist who is free exactly
 * 5–8 PM beats one who is otherwise identical but day-only.
 *
 * Everything here is illustrative. No real people, organisations or identifiers.
 */

export const seedOrganisations: Organisation[] = [
  {
    id: 'org-1',
    name: 'Meridian Health City',
    type: 'Hospital',
    city: 'Bengaluru, KA',
    gstin: '29AABCM1234F1ZQ',
    cin: 'U85110KA2011PTC057342',
    msmeId: 'UDYAM-KA-03-0114287',
    contactPerson: 'Rukmini Desai',
    contactEmail: 'talent@meridianhealthcity.example',
    verificationStatus: 'Verified',
    submittedOn: '2026-04-12',
    beds: 620,
  },
  {
    id: 'org-2',
    name: 'Sanjeevani Mother & Child',
    type: 'Hospital',
    city: 'Pune, MH',
    gstin: '27AAFCS7781K1ZH',
    cin: 'U85100MH2016PTC281904',
    msmeId: 'UDYAM-MH-26-0093311',
    contactPerson: 'Dr. Prashant Kale',
    contactEmail: 'hr@sanjeevanimc.example',
    verificationStatus: 'Verified',
    submittedOn: '2026-05-02',
    beds: 180,
  },
  {
    id: 'org-3',
    name: 'Aarogya Diagnostics',
    type: 'Diagnostics / Lab',
    city: 'Hyderabad, TS',
    gstin: '36AAGCA4419L1Z2',
    cin: 'U74999TG2019PTC135560',
    msmeId: 'UDYAM-TS-02-0077419',
    contactPerson: 'Shreya Nandan',
    contactEmail: 'careers@aarogyadx.example',
    verificationStatus: 'Pending',
    submittedOn: '2026-09-11',
  },
  {
    id: 'org-4',
    name: 'Nivaran Cardiac Institute',
    type: 'Hospital',
    city: 'Chennai, TN',
    gstin: '33AACCN9920M1ZK',
    cin: 'U85110TN2008PLC066214',
    msmeId: 'UDYAM-TN-18-0041120',
    contactPerson: 'Karthik Subramanian',
    contactEmail: 'recruit@nivarancardiac.example',
    verificationStatus: 'Pending',
    submittedOn: '2026-09-15',
    beds: 240,
  },
  {
    id: 'org-5',
    name: 'Tarunya Polyclinic Network',
    type: 'Clinic',
    city: 'Kochi, KL',
    gstin: '32AAHCT3388P1ZD',
    cin: 'U85190KL2021PTC069877',
    msmeId: 'UDYAM-KL-07-0028904',
    contactPerson: 'Anil Menon',
    contactEmail: 'people@tarunyaclinics.example',
    verificationStatus: 'Pending',
    submittedOn: '2026-09-17',
  },
  {
    id: 'org-6',
    name: 'Vedaant Oncology Centre',
    type: 'Hospital',
    city: 'Delhi NCR',
    gstin: '07AAECV6612R1ZN',
    cin: 'U85300DL2014PTC271883',
    msmeId: 'UDYAM-DL-05-0060732',
    contactPerson: 'Farida Qureshi',
    contactEmail: 'hiring@vedaantonco.example',
    verificationStatus: 'On hold',
    submittedOn: '2026-08-29',
    beds: 150,
  },
  {
    id: 'org-7',
    name: 'Prabhu Rural Health Mission',
    type: 'Clinic',
    city: 'Ahmedabad, GJ',
    gstin: '24AAJCP1177T1ZB',
    cin: 'U85110GJ2018NPL102446',
    msmeId: 'UDYAM-GJ-01-0033518',
    contactPerson: 'Dr. Nikhil Trivedi',
    contactEmail: 'admin@prabhurural.example',
    verificationStatus: 'Pending',
    submittedOn: '2026-09-18',
  },
  {
    id: 'org-8',
    name: 'Helix Biosciences',
    type: 'Pharma',
    city: 'Mumbai, MH',
    gstin: '27AAGCH8842W1ZY',
    cin: 'U24239MH2013PTC248811',
    msmeId: 'UDYAM-MH-19-0071203',
    contactPerson: 'Sarika Bhandari',
    contactEmail: 'talent@helixbio.example',
    verificationStatus: 'Verified',
    submittedOn: '2026-06-21',
  },
];

export const seedJobs: Job[] = [
  {
    id: 'job-1',
    title: 'Consultant Obstetrician & Gynaecologist',
    organisationId: 'org-1',
    roleType: 'Doctor / Consultant',
    specialty: 'Obstetrics & Gynaecology',
    subSpecialty: 'High-risk obstetrics',
    minYearsInSpecialty: 8,
    requiredCredentials: ['NMC registration (national)', 'State Medical Council registration', 'BLS certification'],
    shift: 'Day',
    employmentType: 'Full-time',
    location: 'Bengaluru, KA',
    salaryBand: '₹36–48 LPA',
    positionsOpen: 2,
    description:
      'Lead the high-risk obstetrics unit across a 24-bed maternity block. Independent operating list expected from week one, including emergency caesarean cover on a shared rota.',
    surgical: { required: true, role: 'Primary / lead surgeon', minCaseVolume: 100 },
    status: 'Open',
    postedOn: '2026-08-24',
  },
  {
    id: 'job-2',
    title: 'Visiting Cardiologist — evening OPD',
    organisationId: 'org-1',
    roleType: 'Doctor / Consultant',
    specialty: 'Cardiology',
    subSpecialty: 'Non-invasive cardiology',
    minYearsInSpecialty: 5,
    requiredCredentials: ['NMC registration (national)', 'State Medical Council registration'],
    shift: '5–8 PM OPD slot',
    employmentType: 'Consultant (fee-for-service)',
    location: 'Bengaluru, KA',
    salaryBand: '₹18–24k per session',
    positionsOpen: 1,
    description:
      'Run the 5–8 PM cardiology OPD four evenings a week, with echo reporting. No inpatient or cath-lab commitment — this is a strict evening-slot engagement.',
    surgical: { required: false, role: 'Assisting', minCaseVolume: 0 },
    status: 'Open',
    postedOn: '2026-09-02',
  },
  {
    id: 'job-3',
    title: 'ICU Staff Nurse — critical care',
    organisationId: 'org-1',
    roleType: 'Nurse',
    specialty: 'Critical Care',
    subSpecialty: 'ICU / critical care nursing',
    minYearsInSpecialty: 3,
    requiredCredentials: [
      'Indian Nursing Council registration',
      'State Nursing Council registration',
      'BLS certification',
      'ACLS certification',
    ],
    shift: 'Rotational',
    employmentType: 'Full-time',
    location: 'Bengaluru, KA',
    salaryBand: '₹4.8–6.6 LPA',
    positionsOpen: 6,
    description:
      'Rotational cover for a 30-bed mixed medical–surgical ICU. Ventilator and CRRT exposure preferred; structured induction provided.',
    surgical: { required: false, role: 'Assisting', minCaseVolume: 0 },
    status: 'Open',
    postedOn: '2026-08-30',
  },
  {
    id: 'job-4',
    title: 'Neonatal Nurse — NICU Level III',
    organisationId: 'org-2',
    roleType: 'Nurse',
    specialty: 'Paediatrics / Neonatology',
    subSpecialty: 'Neonatal nursing',
    minYearsInSpecialty: 4,
    requiredCredentials: [
      'Indian Nursing Council registration',
      'NRP (Neonatal Resuscitation) certification',
      'BLS certification',
    ],
    shift: 'Night',
    employmentType: 'Full-time',
    location: 'Pune, MH',
    salaryBand: '₹5.4–7.2 LPA',
    positionsOpen: 3,
    description:
      'Night cover for a Level III NICU running 18 cots. Surfactant administration and transport-incubator handovers form part of the role.',
    surgical: { required: false, role: 'Assisting', minCaseVolume: 0 },
    status: 'Open',
    postedOn: '2026-09-05',
  },
  {
    id: 'job-5',
    title: 'MRI Technologist',
    organisationId: 'org-3',
    roleType: 'Diagnostic technician',
    specialty: 'Radiology',
    subSpecialty: 'MRI',
    minYearsInSpecialty: 3,
    requiredCredentials: ['AERB radiation safety clearance', 'BLS certification'],
    shift: 'Rotational',
    employmentType: 'Full-time',
    location: 'Hyderabad, TS',
    salaryBand: '₹4.2–5.8 LPA',
    positionsOpen: 2,
    description:
      'Operate a 3T scanner across a two-shift rota, including contrast studies and paediatric sedation lists with the anaesthesia team.',
    surgical: { required: false, role: 'Assisting', minCaseVolume: 0 },
    status: 'Open',
    postedOn: '2026-09-08',
  },
  {
    id: 'job-6',
    title: 'Registrar — Emergency Medicine',
    organisationId: 'org-2',
    roleType: 'Doctor / Consultant',
    specialty: 'Emergency Medicine',
    subSpecialty: 'Trauma & casualty',
    minYearsInSpecialty: 2,
    requiredCredentials: [
      'NMC registration (national)',
      'BLS certification',
      'ACLS certification',
    ],
    shift: 'Rotational',
    employmentType: 'Full-time',
    location: 'Pune, MH',
    salaryBand: '₹14–19 LPA',
    positionsOpen: 2,
    description:
      'Front-of-house casualty cover on a 3-shift rota with consultant backup. Around 190 footfalls a day, roughly a fifth of them trauma.',
    surgical: { required: false, role: 'Assisting', minCaseVolume: 0 },
    status: 'Paused',
    postedOn: '2026-07-19',
  },
  {
    id: 'job-7',
    title: 'Histopathology Lab Technologist — part-time',
    organisationId: 'org-3',
    roleType: 'Lab technologist',
    specialty: 'Pathology',
    subSpecialty: 'Histopathology',
    minYearsInSpecialty: 2,
    requiredCredentials: ['NABL-lab competency sign-off'],
    shift: 'Part-time / Locum',
    employmentType: 'Part-time',
    location: 'Hyderabad, TS',
    salaryBand: '₹2.8–3.6 LPA (pro-rata)',
    positionsOpen: 1,
    description:
      'Grossing support and routine H&E workload across three mornings a week in a NABL-accredited lab.',
    surgical: { required: false, role: 'Assisting', minCaseVolume: 0 },
    status: 'Open',
    postedOn: '2026-09-12',
  },
  {
    id: 'job-8',
    title: 'Orthopaedic Surgeon — arthroplasty list',
    organisationId: 'org-1',
    roleType: 'Doctor / Consultant',
    specialty: 'Orthopaedics',
    subSpecialty: 'Arthroplasty',
    minYearsInSpecialty: 7,
    requiredCredentials: ['NMC registration (national)', 'State Medical Council registration'],
    shift: 'Day',
    employmentType: 'Full-time',
    location: 'Bengaluru, KA',
    salaryBand: '₹42–55 LPA',
    positionsOpen: 1,
    description:
      'Own a twice-weekly arthroplasty list (primary knees and hips) with revision work shared across the unit.',
    surgical: { required: true, role: 'Primary / lead surgeon', minCaseVolume: 150 },
    status: 'Open',
    postedOn: '2026-09-01',
  },
  {
    id: 'job-9',
    title: 'Consultant Anaesthetist — obstetric list',
    organisationId: 'org-2',
    roleType: 'Doctor / Consultant',
    specialty: 'Anaesthesia',
    subSpecialty: 'Obstetric anaesthesia',
    minYearsInSpecialty: 5,
    requiredCredentials: [
      'NMC registration (national)',
      'State Medical Council registration',
      'ACLS certification',
    ],
    shift: 'On-call',
    employmentType: 'Full-time',
    location: 'Pune, MH',
    salaryBand: '₹28–36 LPA',
    positionsOpen: 1,
    description:
      'Cover the obstetric theatre list and the epidural service, with a shared on-call rota across four consultants.',
    surgical: { required: true, role: 'Assisting', minCaseVolume: 200 },
    status: 'Open',
    postedOn: '2026-09-09',
  },
  {
    id: 'job-10',
    title: 'Clinical Pharmacist — oncology day care',
    organisationId: 'org-6',
    roleType: 'Pharmacist',
    specialty: 'Oncology',
    subSpecialty: 'Medical oncology',
    minYearsInSpecialty: 3,
    requiredCredentials: ['Pharmacy Council registration', 'BLS certification'],
    shift: 'Day',
    employmentType: 'Full-time',
    location: 'Delhi NCR',
    salaryBand: '₹6.5–9 LPA',
    positionsOpen: 1,
    description:
      'Chemotherapy dose verification and counselling across a 14-chair day-care unit, working alongside the medical oncology team.',
    surgical: { required: false, role: 'Assisting', minCaseVolume: 0 },
    status: 'Open',
    postedOn: '2026-09-14',
  },
  {
    id: 'job-11',
    title: 'Senior Physiotherapist — neuro rehabilitation',
    organisationId: 'org-5',
    roleType: 'Allied health',
    specialty: 'Physiotherapy',
    subSpecialty: 'Neuro rehabilitation',
    minYearsInSpecialty: 4,
    requiredCredentials: ['BLS certification'],
    shift: 'Day',
    employmentType: 'Full-time',
    location: 'Kochi, KL',
    salaryBand: '₹5–7 LPA',
    positionsOpen: 2,
    description:
      'Lead the neuro-rehab caseload across the polyclinic network, including post-stroke and spinal-injury programmes.',
    surgical: { required: false, role: 'Assisting', minCaseVolume: 0 },
    status: 'Open',
    postedOn: '2026-09-16',
  },
  {
    id: 'job-12',
    title: 'Hospital Operations Manager',
    organisationId: 'org-1',
    roleType: 'Hospital administration / management',
    specialty: 'General Medicine',
    subSpecialty: 'Ward management',
    minYearsInSpecialty: 6,
    requiredCredentials: ['Fire & safety mandatory training'],
    shift: 'Day',
    employmentType: 'Full-time',
    location: 'Bengaluru, KA',
    salaryBand: '₹16–22 LPA',
    positionsOpen: 1,
    description:
      'Own bed management, housekeeping and patient-flow SLAs across three inpatient blocks; NABH readiness is part of the brief.',
    surgical: { required: false, role: 'Assisting', minCaseVolume: 0 },
    status: 'Closed',
    postedOn: '2026-06-04',
  },
];

export const seedCandidates: Candidate[] = [
  {
    id: 'cand-1',
    fullName: 'Dr. Ananya Rao',
    roleType: 'Doctor / Consultant',
    headline: 'Consultant O&G · high-risk obstetrics · 11 years',
    specialties: [
      { specialty: 'Obstetrics & Gynaecology', years: 11, subSpecialties: ['High-risk obstetrics', 'Obstetric OT'] },
    ],
    credentials: [
      'NMC registration (national)',
      'State Medical Council registration',
      'BLS certification',
      'ACLS certification',
    ],
    availability: ['Day', 'On-call'],
    preferredLocations: ['Bengaluru, KA', 'Hyderabad, TS'],
    employmentTypePreference: ['Full-time'],
    surgical: {
      performed: true,
      role: 'Primary / lead surgeon',
      caseVolume: 240,
      notableProcedures: 'Emergency and elective caesarean section, hysterectomy, cerclage',
    },
    consentToShare: true,
    contactEmail: 'ananya.rao@example.in',
    contactPhone: '+91 98450 11234',
    currentEmployer: 'Lotus Women’s Hospital',
    noticePeriod: '60 days',
  },
  {
    id: 'cand-2',
    fullName: 'Dr. Vikram Iyer',
    roleType: 'Doctor / Consultant',
    headline: 'O&G registrar · 6 years · assisting theatre experience',
    specialties: [
      { specialty: 'Obstetrics & Gynaecology', years: 6, subSpecialties: ['High-risk obstetrics'] },
    ],
    credentials: ['NMC registration (national)', 'State Medical Council registration', 'BLS certification'],
    availability: ['Day', 'Rotational'],
    preferredLocations: ['Bengaluru, KA'],
    employmentTypePreference: ['Full-time'],
    surgical: {
      performed: true,
      role: 'Assisting',
      caseVolume: 180,
      notableProcedures: 'Assisted on caesarean sections and laparoscopic gynae lists',
    },
    consentToShare: true,
    contactEmail: 'vikram.iyer@example.in',
    contactPhone: '+91 99020 55871',
    currentEmployer: 'Meridian Health City',
    noticePeriod: '30 days',
  },
  {
    id: 'cand-3',
    fullName: 'Dr. Meera Krishnan',
    roleType: 'Doctor / Consultant',
    headline: 'Cardiologist · non-invasive · available 5–8 PM only',
    specialties: [
      { specialty: 'Cardiology', years: 9, subSpecialties: ['Non-invasive cardiology', 'Echocardiography'] },
    ],
    credentials: ['NMC registration (national)', 'State Medical Council registration', 'BLS certification'],
    availability: ['5–8 PM OPD slot', 'Weekend only'],
    preferredLocations: ['Bengaluru, KA'],
    employmentTypePreference: ['Consultant (fee-for-service)', 'Part-time'],
    surgical: { performed: false, role: 'Assisting', caseVolume: 0, notableProcedures: '' },
    consentToShare: true,
    contactEmail: 'meera.krishnan@example.in',
    contactPhone: '+91 90080 47712',
    currentEmployer: 'Private practice',
    noticePeriod: 'Immediate',
  },
  {
    id: 'cand-4',
    fullName: 'Dr. Rajat Bhatia',
    roleType: 'Doctor / Consultant',
    headline: 'Cardiologist · interventional · day shifts only',
    specialties: [
      { specialty: 'Cardiology', years: 12, subSpecialties: ['Interventional cardiology', 'Cath lab'] },
    ],
    credentials: ['NMC registration (national)', 'State Medical Council registration'],
    availability: ['Day', 'On-call'],
    preferredLocations: ['Bengaluru, KA', 'Delhi NCR'],
    employmentTypePreference: ['Full-time'],
    surgical: {
      performed: true,
      role: 'Primary / lead surgeon',
      caseVolume: 900,
      notableProcedures: 'Coronary angioplasty, pacemaker implantation',
    },
    consentToShare: true,
    contactEmail: 'rajat.bhatia@example.in',
    contactPhone: '+91 98110 30045',
    currentEmployer: 'Nivaran Cardiac Institute',
    noticePeriod: '90 days',
  },
  {
    id: 'cand-5',
    fullName: 'Sister Latha Nair',
    roleType: 'Nurse',
    headline: 'ICU staff nurse · 7 years critical care · rotational',
    specialties: [
      { specialty: 'Critical Care', years: 7, subSpecialties: ['ICU / critical care nursing', 'Ventilator management'] },
    ],
    credentials: [
      'Indian Nursing Council registration',
      'State Nursing Council registration',
      'BLS certification',
      'ACLS certification',
    ],
    availability: ['Rotational', 'Night'],
    preferredLocations: ['Bengaluru, KA', 'Kochi, KL'],
    employmentTypePreference: ['Full-time'],
    surgical: { performed: false, role: 'Assisting', caseVolume: 0, notableProcedures: '' },
    consentToShare: true,
    contactEmail: 'latha.nair@example.in',
    contactPhone: '+91 94470 22318',
    currentEmployer: 'Tarunya Polyclinic Network',
    noticePeriod: '30 days',
  },
  {
    id: 'cand-6',
    fullName: 'Sister Pooja Deshmukh',
    roleType: 'Nurse',
    headline: 'ICU nurse · 4 years · no ACLS yet',
    specialties: [
      { specialty: 'Critical Care', years: 4, subSpecialties: ['ICU / critical care nursing'] },
    ],
    credentials: ['Indian Nursing Council registration', 'State Nursing Council registration', 'BLS certification'],
    availability: ['Rotational', 'Day'],
    preferredLocations: ['Bengaluru, KA', 'Pune, MH'],
    employmentTypePreference: ['Full-time', 'Contract'],
    surgical: { performed: false, role: 'Assisting', caseVolume: 0, notableProcedures: '' },
    consentToShare: true,
    contactEmail: 'pooja.deshmukh@example.in',
    contactPhone: '+91 90280 66104',
    currentEmployer: 'Sanjeevani Mother & Child',
    noticePeriod: '45 days',
  },
  {
    id: 'cand-7',
    fullName: 'Sister Grace Fernandes',
    roleType: 'Nurse',
    headline: 'Neonatal nurse · NICU Level III · 6 years · nights',
    specialties: [
      { specialty: 'Paediatrics / Neonatology', years: 6, subSpecialties: ['NICU'] },
    ],
    credentials: [
      'Indian Nursing Council registration',
      'NRP (Neonatal Resuscitation) certification',
      'BLS certification',
      'State Nursing Council registration',
    ],
    availability: ['Night', 'Rotational'],
    preferredLocations: ['Pune, MH', 'Mumbai, MH'],
    employmentTypePreference: ['Full-time'],
    surgical: { performed: false, role: 'Assisting', caseVolume: 0, notableProcedures: '' },
    consentToShare: true,
    contactEmail: 'grace.fernandes@example.in',
    contactPhone: '+91 98220 41190',
    currentEmployer: 'Aster Mother & Child',
    noticePeriod: '60 days',
  },
  {
    id: 'cand-8',
    fullName: 'Sister Kavya Reddy',
    roleType: 'Nurse',
    headline: 'Paediatric ward nurse · 5 years · moving toward neonatal',
    specialties: [
      { specialty: 'Obstetrics & Gynaecology', years: 5, subSpecialties: ['Maternity & neonatal nursing'] },
      { specialty: 'Paediatrics / Neonatology', years: 3, subSpecialties: ['Paediatric emergency'] },
    ],
    credentials: [
      'Indian Nursing Council registration',
      'NRP (Neonatal Resuscitation) certification',
      'BLS certification',
    ],
    availability: ['Day', 'Rotational'],
    preferredLocations: ['Hyderabad, TS', 'Pune, MH'],
    employmentTypePreference: ['Full-time'],
    surgical: {
      performed: true,
      role: 'Assisting',
      caseVolume: 60,
      notableProcedures: 'Scrub nurse on caesarean lists',
    },
    consentToShare: true,
    contactEmail: 'kavya.reddy@example.in',
    contactPhone: '+91 89850 77321',
    currentEmployer: 'Aarogya Diagnostics',
    noticePeriod: '30 days',
  },
  {
    id: 'cand-9',
    fullName: 'Imran Shaikh',
    roleType: 'Diagnostic technician',
    headline: 'MRI technologist · 3T · 5 years · AERB cleared',
    specialties: [{ specialty: 'Radiology', years: 5, subSpecialties: ['MRI', 'CT'] }],
    credentials: ['AERB radiation safety clearance', 'BLS certification'],
    availability: ['Evening'],
    preferredLocations: ['Hyderabad, TS', 'Pune, MH'],
    employmentTypePreference: ['Full-time', 'Contract'],
    surgical: { performed: false, role: 'Assisting', caseVolume: 0, notableProcedures: '' },
    consentToShare: true,
    contactEmail: 'imran.shaikh@example.in',
    contactPhone: '+91 91770 30988',
    currentEmployer: 'City Scan Centre',
    noticePeriod: 'Immediate',
  },
  {
    id: 'cand-10',
    fullName: 'Nandita Sen',
    roleType: 'Diagnostic technician',
    headline: 'Ultrasound & X-ray technician · 4 years · no AERB clearance on file',
    specialties: [{ specialty: 'Radiology', years: 4, subSpecialties: ['Ultrasound', 'X-ray / general radiography'] }],
    credentials: ['BLS certification'],
    availability: ['Day', 'Rotational'],
    preferredLocations: ['Hyderabad, TS'],
    employmentTypePreference: ['Full-time'],
    surgical: { performed: false, role: 'Assisting', caseVolume: 0, notableProcedures: '' },
    consentToShare: true,
    contactEmail: 'nandita.sen@example.in',
    contactPhone: '+91 70360 12844',
    currentEmployer: 'Sunrise Imaging',
    noticePeriod: '15 days',
  },
  {
    id: 'cand-11',
    fullName: 'Dr. Sneha Pillai',
    roleType: 'Doctor / Consultant',
    headline: 'Emergency medicine registrar · 3 years · rotational',
    specialties: [
      { specialty: 'Emergency Medicine', years: 3, subSpecialties: ['Trauma & casualty', 'Triage'] },
    ],
    credentials: ['NMC registration (national)', 'BLS certification', 'ACLS certification'],
    availability: ['Rotational', 'Night'],
    preferredLocations: ['Mumbai, MH'],
    employmentTypePreference: ['Full-time'],
    surgical: { performed: false, role: 'Assisting', caseVolume: 0, notableProcedures: '' },
    consentToShare: true,
    contactEmail: 'sneha.pillai@example.in',
    contactPhone: '+91 99670 51203',
    currentEmployer: 'Ruby Hall Casualty',
    noticePeriod: '30 days',
  },
  {
    id: 'cand-12',
    fullName: 'Arvind Kulkarni',
    roleType: 'Lab technologist',
    headline: 'Histopathology technologist · 6 years · part-time sought',
    specialties: [{ specialty: 'Pathology', years: 6, subSpecialties: ['Histopathology', 'Clinical biochemistry'] }],
    credentials: ['NABL-lab competency sign-off'],
    availability: ['Part-time / Locum', 'Day'],
    preferredLocations: ['Hyderabad, TS'],
    employmentTypePreference: ['Part-time', 'Locum / Visiting'],
    surgical: { performed: false, role: 'Assisting', caseVolume: 0, notableProcedures: '' },
    consentToShare: true,
    contactEmail: 'arvind.kulkarni@example.in',
    contactPhone: '+91 94910 67450',
    currentEmployer: 'Deccan Path Labs',
    noticePeriod: '15 days',
  },
  {
    id: 'cand-13',
    fullName: 'Dr. Harpreet Sandhu',
    roleType: 'Doctor / Consultant',
    headline: 'Orthopaedic surgeon · arthroplasty · 9 years · 310 primary cases',
    specialties: [
      { specialty: 'Orthopaedics', years: 9, subSpecialties: ['Arthroplasty', 'Sports injury'] },
    ],
    credentials: ['NMC registration (national)', 'State Medical Council registration', 'BLS certification'],
    availability: ['Day', 'On-call'],
    preferredLocations: ['Bengaluru, KA', 'Delhi NCR'],
    employmentTypePreference: ['Full-time'],
    surgical: {
      performed: true,
      role: 'Primary / lead surgeon',
      caseVolume: 310,
      notableProcedures: 'Total knee and hip arthroplasty, revision arthroplasty',
    },
    consentToShare: true,
    contactEmail: 'harpreet.sandhu@example.in',
    contactPhone: '+91 98760 22981',
    currentEmployer: 'Apex Bone & Joint',
    noticePeriod: '90 days',
  },
  {
    id: 'cand-14',
    fullName: 'Dr. Tanvi Joshi',
    roleType: 'Doctor / Consultant',
    headline: 'Orthopaedic surgeon · 8 years · 40 primary arthroplasty cases',
    specialties: [
      { specialty: 'Orthopaedics', years: 8, subSpecialties: ['Arthroplasty', 'Spine'] },
    ],
    credentials: ['NMC registration (national)', 'State Medical Council registration'],
    availability: ['Day'],
    preferredLocations: ['Bengaluru, KA'],
    employmentTypePreference: ['Full-time', 'Contract'],
    surgical: {
      performed: true,
      role: 'Primary / lead surgeon',
      caseVolume: 40,
      notableProcedures: 'Primary knee arthroplasty, trauma fixation',
    },
    consentToShare: false,
    contactEmail: 'tanvi.joshi@example.in',
    contactPhone: '+91 97300 18866',
    currentEmployer: 'Sahyadri Ortho Centre',
    noticePeriod: '60 days',
  },
  {
    id: 'cand-15',
    fullName: 'Dr. Leena Mathew',
    roleType: 'Doctor / Consultant',
    headline: 'Consultant anaesthetist · obstetric lists · 8 years',
    specialties: [
      { specialty: 'Anaesthesia', years: 8, subSpecialties: ['Obstetric anaesthesia', 'OT anaesthesia technician'] },
    ],
    credentials: [
      'NMC registration (national)',
      'State Medical Council registration',
      'ACLS certification',
      'BLS certification',
    ],
    availability: ['On-call', 'Day'],
    preferredLocations: ['Pune, MH', 'Mumbai, MH'],
    employmentTypePreference: ['Full-time'],
    surgical: {
      performed: true,
      role: 'Assisting',
      caseVolume: 640,
      notableProcedures: 'Obstetric epidurals, spinal anaesthesia for caesarean lists',
    },
    consentToShare: true,
    contactEmail: 'leena.mathew@example.in',
    contactPhone: '+91 98600 71422',
    currentEmployer: 'Deenanath Hospital',
    noticePeriod: '60 days',
  },
  {
    id: 'cand-16',
    fullName: 'Dr. Suresh Patil',
    roleType: 'Doctor / Consultant',
    headline: 'Anaesthetist · 4 years · no ACLS on file',
    specialties: [{ specialty: 'Anaesthesia', years: 4, subSpecialties: ['Cardiac anaesthesia'] }],
    credentials: ['NMC registration (national)', 'State Medical Council registration'],
    availability: ['Rotational'],
    preferredLocations: ['Pune, MH'],
    employmentTypePreference: ['Full-time', 'Contract'],
    surgical: {
      performed: true,
      role: 'Assisting',
      caseVolume: 150,
      notableProcedures: 'Cardiac theatre assistance',
    },
    consentToShare: true,
    contactEmail: 'suresh.patil@example.in',
    contactPhone: '+91 97640 28810',
    currentEmployer: 'Sahyadri Hospital',
    noticePeriod: '30 days',
  },
  {
    id: 'cand-17',
    fullName: 'Rhea D’Souza',
    roleType: 'Pharmacist',
    headline: 'Clinical pharmacist · oncology day care · 5 years',
    specialties: [{ specialty: 'Oncology', years: 5, subSpecialties: ['Medical oncology', 'Oncology day-care nursing'] }],
    credentials: ['Pharmacy Council registration', 'BLS certification'],
    availability: ['Day'],
    preferredLocations: ['Delhi NCR', 'Mumbai, MH'],
    employmentTypePreference: ['Full-time'],
    surgical: { performed: false, role: 'Assisting', caseVolume: 0, notableProcedures: '' },
    consentToShare: true,
    contactEmail: 'rhea.dsouza@example.in',
    contactPhone: '+91 98190 55276',
    currentEmployer: 'Vedaant Oncology Centre',
    noticePeriod: '45 days',
  },
  {
    id: 'cand-18',
    fullName: 'Mohit Saxena',
    roleType: 'Pharmacist',
    headline: 'Retail pharmacist moving to clinical · 3 years',
    specialties: [{ specialty: 'Oncology', years: 2, subSpecialties: ['Medical oncology'] }],
    credentials: ['Pharmacy Council registration'],
    availability: ['Day', 'Evening'],
    preferredLocations: ['Delhi NCR'],
    employmentTypePreference: ['Full-time'],
    surgical: { performed: false, role: 'Assisting', caseVolume: 0, notableProcedures: '' },
    consentToShare: true,
    contactEmail: 'mohit.saxena@example.in',
    contactPhone: '+91 98110 90441',
    currentEmployer: 'Wellness Chemists',
    noticePeriod: 'Immediate',
  },
  {
    id: 'cand-19',
    fullName: 'Anjali Varma',
    roleType: 'Allied health',
    headline: 'Senior physiotherapist · neuro rehab · 7 years',
    specialties: [
      { specialty: 'Physiotherapy', years: 7, subSpecialties: ['Neuro rehabilitation', 'Musculoskeletal'] },
    ],
    credentials: ['BLS certification'],
    availability: ['Day', 'Part-time / Locum'],
    preferredLocations: ['Kochi, KL', 'Chennai, TN'],
    employmentTypePreference: ['Full-time', 'Part-time'],
    surgical: { performed: false, role: 'Assisting', caseVolume: 0, notableProcedures: '' },
    consentToShare: true,
    contactEmail: 'anjali.varma@example.in',
    contactPhone: '+91 94470 88132',
    currentEmployer: 'Amrita Rehab',
    noticePeriod: '30 days',
  },
  {
    id: 'cand-20',
    fullName: 'Thomas Kurian',
    roleType: 'Allied health',
    headline: 'Physiotherapist · musculoskeletal focus · 5 years',
    specialties: [{ specialty: 'Physiotherapy', years: 5, subSpecialties: ['Musculoskeletal', 'Cardio-pulmonary rehab'] }],
    credentials: ['BLS certification'],
    availability: ['Day'],
    preferredLocations: ['Kochi, KL'],
    employmentTypePreference: ['Full-time'],
    surgical: { performed: false, role: 'Assisting', caseVolume: 0, notableProcedures: '' },
    consentToShare: true,
    contactEmail: 'thomas.kurian@example.in',
    contactPhone: '+91 90720 34109',
    currentEmployer: 'Tarunya Polyclinic Network',
    noticePeriod: '15 days',
  },
  {
    id: 'cand-21',
    fullName: 'Sister Rekha Balan',
    roleType: 'Nurse',
    headline: 'OT scrub nurse · 9 years · orthopaedic lists',
    specialties: [
      { specialty: 'Orthopaedics', years: 9, subSpecialties: ['OT / orthopaedic assistance'] },
      { specialty: 'Critical Care', years: 3, subSpecialties: ['ICU / critical care nursing'] },
    ],
    credentials: [
      'Indian Nursing Council registration',
      'State Nursing Council registration',
      'BLS certification',
    ],
    availability: ['Day', 'On-call'],
    preferredLocations: ['Bengaluru, KA'],
    employmentTypePreference: ['Full-time'],
    surgical: {
      performed: true,
      role: 'Assisting',
      caseVolume: 1200,
      notableProcedures: 'Scrub nurse on arthroplasty and trauma lists',
    },
    consentToShare: true,
    contactEmail: 'rekha.balan@example.in',
    contactPhone: '+91 99860 44271',
    currentEmployer: 'Apex Bone & Joint',
    noticePeriod: '60 days',
  },
  {
    id: 'cand-22',
    fullName: 'Dr. Prakash Menon',
    roleType: 'Doctor / Consultant',
    headline: 'Radiologist · MRI & interventional · 10 years',
    specialties: [
      { specialty: 'Radiology', years: 10, subSpecialties: ['MRI', 'Interventional radiology'] },
    ],
    credentials: [
      'NMC registration (national)',
      'State Medical Council registration',
      'AERB radiation safety clearance',
    ],
    availability: ['Day', 'Rotational'],
    preferredLocations: ['Hyderabad, TS', 'Kochi, KL'],
    employmentTypePreference: ['Full-time', 'Consultant (fee-for-service)'],
    surgical: {
      performed: true,
      role: 'Primary / lead surgeon',
      caseVolume: 420,
      notableProcedures: 'Image-guided biopsy, drainage, angioplasty',
    },
    consentToShare: false,
    contactEmail: 'prakash.menon@example.in',
    contactPhone: '+91 98490 11763',
    currentEmployer: 'Aarogya Diagnostics',
    noticePeriod: '90 days',
  },
  {
    id: 'cand-23',
    fullName: 'Fatima Sheikh',
    roleType: 'Lab technologist',
    headline: 'Haematology technologist · 4 years · NABL lab',
    specialties: [{ specialty: 'Pathology', years: 4, subSpecialties: ['Haematology', 'Clinical biochemistry'] }],
    credentials: ['NABL-lab competency sign-off', 'BLS certification'],
    availability: ['Day', 'Rotational'],
    preferredLocations: ['Hyderabad, TS', 'Mumbai, MH'],
    employmentTypePreference: ['Full-time'],
    surgical: { performed: false, role: 'Assisting', caseVolume: 0, notableProcedures: '' },
    consentToShare: true,
    contactEmail: 'fatima.sheikh@example.in',
    contactPhone: '+91 91000 27384',
    currentEmployer: 'Deccan Path Labs',
    noticePeriod: '30 days',
  },
  {
    id: 'cand-24',
    fullName: 'Ravi Gopalan',
    roleType: 'Hospital administration / management',
    headline: 'Hospital operations · 8 years · multi-block',
    specialties: [{ specialty: 'General Medicine', years: 8, subSpecialties: ['Ward management'] }],
    credentials: ['Fire & safety mandatory training'],
    availability: ['Day'],
    preferredLocations: ['Bengaluru, KA', 'Chennai, TN'],
    employmentTypePreference: ['Full-time'],
    surgical: { performed: false, role: 'Assisting', caseVolume: 0, notableProcedures: '' },
    consentToShare: true,
    contactEmail: 'ravi.gopalan@example.in',
    contactPhone: '+91 99450 60218',
    currentEmployer: 'Columbia Asia',
    noticePeriod: '60 days',
  },
];

export const seedApplications: Application[] = [
  {
    id: 'app-1',
    jobId: 'job-1',
    candidateId: 'cand-1',
    stage: 'Interview',
    appliedOn: '2026-08-27',
    updatedOn: '2026-09-10',
    shortlisted: true,
    source: 'Candidate applied',
    notes: [
      { id: 'note-1', stage: 'Shortlisted', text: 'Operative log verified against theatre records.', addedOn: '2026-09-01' },
      { id: 'note-2', stage: 'Interview', text: 'Panel set for 22 Sep, 11:00. Clinical head attending.', addedOn: '2026-09-10' },
    ],
  },
  {
    id: 'app-2',
    jobId: 'job-1',
    candidateId: 'cand-2',
    stage: 'Applied',
    appliedOn: '2026-09-03',
    updatedOn: '2026-09-03',
    shortlisted: false,
    source: 'Candidate applied',
    notes: [],
  },
  {
    id: 'app-3',
    jobId: 'job-2',
    candidateId: 'cand-3',
    stage: 'Offer',
    appliedOn: '2026-09-04',
    updatedOn: '2026-09-16',
    shortlisted: true,
    source: 'Sourced by employer',
    notes: [
      { id: 'note-3', stage: 'Shortlisted', text: 'Confirmed she can hold the 5–8 PM slot four evenings.', addedOn: '2026-09-08' },
      { id: 'note-4', stage: 'Offer', text: 'Session rate agreed at ₹21k; paperwork with finance.', addedOn: '2026-09-16' },
    ],
  },
  {
    id: 'app-4',
    jobId: 'job-2',
    candidateId: 'cand-4',
    stage: 'Applied',
    appliedOn: '2026-09-06',
    updatedOn: '2026-09-06',
    shortlisted: false,
    source: 'Candidate applied',
    notes: [],
  },
  {
    id: 'app-5',
    jobId: 'job-3',
    candidateId: 'cand-5',
    stage: 'Joined',
    appliedOn: '2026-07-28',
    updatedOn: '2026-09-01',
    shortlisted: true,
    source: 'Candidate applied',
    notes: [
      { id: 'note-5', stage: 'Offer', text: 'Offer accepted, joining 1 Sep.', addedOn: '2026-08-20' },
      { id: 'note-6', stage: 'Joined', text: 'Induction complete, assigned to Unit B.', addedOn: '2026-09-01' },
    ],
  },
  {
    id: 'app-6',
    jobId: 'job-3',
    candidateId: 'cand-6',
    stage: 'Shortlisted',
    appliedOn: '2026-09-09',
    updatedOn: '2026-09-14',
    shortlisted: true,
    source: 'Candidate applied',
    notes: [
      { id: 'note-7', stage: 'Shortlisted', text: 'ACLS pending — hospital can sponsor within probation.', addedOn: '2026-09-14' },
    ],
  },
  {
    id: 'app-7',
    jobId: 'job-4',
    candidateId: 'cand-7',
    stage: 'Interview',
    appliedOn: '2026-09-07',
    updatedOn: '2026-09-15',
    shortlisted: true,
    source: 'Candidate applied',
    notes: [
      { id: 'note-8', stage: 'Interview', text: 'Night-shift preference confirmed in screening call.', addedOn: '2026-09-15' },
    ],
  },
  {
    // Same NICU role as app-7 — she clears every gate but is junior for the unit, which
    // is what a "Good" rather than "Strong" fit looks like side by side.
    id: 'app-12',
    jobId: 'job-4',
    candidateId: 'cand-8',
    stage: 'Applied',
    appliedOn: '2026-09-14',
    updatedOn: '2026-09-14',
    shortlisted: false,
    source: 'Candidate applied',
    notes: [],
  },
  {
    id: 'app-8',
    jobId: 'job-5',
    candidateId: 'cand-9',
    stage: 'Shortlisted',
    appliedOn: '2026-09-10',
    updatedOn: '2026-09-13',
    shortlisted: true,
    source: 'Candidate applied',
    notes: [],
  },
  {
    id: 'app-9',
    jobId: 'job-8',
    candidateId: 'cand-13',
    stage: '90-day follow-up',
    appliedOn: '2026-05-14',
    updatedOn: '2026-09-12',
    shortlisted: true,
    source: 'Sourced by employer',
    notes: [
      { id: 'note-9', stage: 'Joined', text: 'Joined 12 Jun, arthroplasty list live from week two.', addedOn: '2026-06-12' },
      { id: 'note-10', stage: '90-day follow-up', text: '90-day review done — retention confirmed.', addedOn: '2026-09-12' },
    ],
  },
  {
    id: 'app-10',
    jobId: 'job-8',
    candidateId: 'cand-14',
    stage: 'Applied',
    appliedOn: '2026-09-11',
    updatedOn: '2026-09-11',
    shortlisted: false,
    source: 'Candidate applied',
    notes: [],
  },
  {
    id: 'app-11',
    jobId: 'job-7',
    candidateId: 'cand-12',
    stage: 'Applied',
    appliedOn: '2026-09-13',
    updatedOn: '2026-09-13',
    shortlisted: false,
    source: 'Candidate applied',
    notes: [],
  },
  {
    id: 'app-13',
    jobId: 'job-9',
    candidateId: 'cand-15',
    stage: 'Offer',
    appliedOn: '2026-09-10',
    updatedOn: '2026-09-17',
    shortlisted: true,
    source: 'Candidate applied',
    notes: [
      { id: 'note-11', stage: 'Interview', text: 'Panel happy with the obstetric epidural volume.', addedOn: '2026-09-15' },
      { id: 'note-12', stage: 'Offer', text: 'Offer at ₹33 LPA sent; awaiting response.', addedOn: '2026-09-17' },
    ],
  },
  {
    id: 'app-14',
    jobId: 'job-9',
    candidateId: 'cand-16',
    stage: 'Applied',
    appliedOn: '2026-09-15',
    updatedOn: '2026-09-15',
    shortlisted: false,
    source: 'Candidate applied',
    notes: [],
  },
  {
    id: 'app-15',
    jobId: 'job-10',
    candidateId: 'cand-17',
    stage: 'Shortlisted',
    appliedOn: '2026-09-16',
    updatedOn: '2026-09-18',
    shortlisted: true,
    source: 'Sourced by employer',
    notes: [
      { id: 'note-13', stage: 'Shortlisted', text: 'Already works the day-care unit — minimal ramp-up.', addedOn: '2026-09-18' },
    ],
  },
  {
    id: 'app-16',
    jobId: 'job-10',
    candidateId: 'cand-18',
    stage: 'Applied',
    appliedOn: '2026-09-17',
    updatedOn: '2026-09-17',
    shortlisted: false,
    source: 'Candidate applied',
    notes: [],
  },
  {
    id: 'app-17',
    jobId: 'job-11',
    candidateId: 'cand-19',
    stage: 'Interview',
    appliedOn: '2026-09-17',
    updatedOn: '2026-09-19',
    shortlisted: true,
    source: 'Candidate applied',
    notes: [
      { id: 'note-14', stage: 'Interview', text: 'Clinical assessment scheduled at the Kochi site.', addedOn: '2026-09-19' },
    ],
  },
  {
    id: 'app-18',
    jobId: 'job-11',
    candidateId: 'cand-20',
    stage: 'Applied',
    appliedOn: '2026-09-18',
    updatedOn: '2026-09-18',
    shortlisted: false,
    source: 'Candidate applied',
    notes: [],
  },
  {
    id: 'app-19',
    jobId: 'job-5',
    candidateId: 'cand-10',
    stage: 'Applied',
    appliedOn: '2026-09-12',
    updatedOn: '2026-09-12',
    shortlisted: false,
    source: 'Candidate applied',
    notes: [],
  },
  {
    id: 'app-20',
    jobId: 'job-12',
    candidateId: 'cand-24',
    stage: '90-day follow-up',
    appliedOn: '2026-04-18',
    updatedOn: '2026-09-08',
    shortlisted: true,
    source: 'Sourced by employer',
    notes: [
      { id: 'note-15', stage: 'Joined', text: 'Joined 2 Jun as operations manager, Block C.', addedOn: '2026-06-02' },
      { id: 'note-16', stage: '90-day follow-up', text: 'Retention confirmed at 90 days; invoice raised.', addedOn: '2026-09-08' },
    ],
  },
  {
    id: 'app-21',
    jobId: 'job-1',
    candidateId: 'cand-21',
    stage: 'Applied',
    appliedOn: '2026-09-19',
    updatedOn: '2026-09-19',
    shortlisted: false,
    source: 'Candidate applied',
    notes: [],
  },
];

export const seedAudit: AuditEntry[] = [
  {
    id: 'audit-1',
    at: '2026-05-02 10:14',
    actor: 'Admin (demo)',
    action: 'Approved organisation',
    target: 'Sanjeevani Mother & Child',
    detail: 'GSTIN and CIN cross-checked against submitted documents.',
  },
  {
    id: 'audit-2',
    at: '2026-04-12 16:41',
    actor: 'Admin (demo)',
    action: 'Approved organisation',
    target: 'Meridian Health City',
    detail: 'Hospital registration and bed count verified.',
  },
  {
    id: 'audit-3',
    at: '2026-08-29 09:05',
    actor: 'Admin (demo)',
    action: 'Placed organisation on hold',
    target: 'Vedaant Oncology Centre',
    detail: 'MSME certificate illegible — re-upload requested.',
  },
];

export const seedRecruiters: Recruiter[] = [
  {
    id: 'rec-1',
    agencyName: 'CaduceusSearch Partners',
    contactPerson: 'Neha Agarwal',
    city: 'Bengaluru, KA',
    specialisations: ['Obstetrics & Gynaecology', 'Orthopaedics', 'Anaesthesia'],
    placementsClosed: 34,
    rating: 4.6,
    acceptedJobIds: ['job-1', 'job-8'],
  },
  {
    id: 'rec-2',
    agencyName: 'VitalStaff Consultancy',
    contactPerson: 'Imtiaz Khan',
    city: 'Pune, MH',
    specialisations: ['Critical Care', 'Paediatrics / Neonatology'],
    placementsClosed: 19,
    rating: 4.2,
    acceptedJobIds: ['job-4'],
  },
];

export const seedSubmissions: Submission[] = [
  {
    id: 'sub-1',
    recruiterId: 'rec-1',
    jobId: 'job-1',
    candidateId: 'cand-1',
    status: 'Interview',
    submittedOn: '2026-08-28',
    note: 'Operative log verified directly with the previous unit head.',
    feeInr: 420000,
    payoutStatus: 'Pending',
  },
  {
    id: 'sub-2',
    recruiterId: 'rec-1',
    jobId: 'job-8',
    candidateId: 'cand-13',
    status: 'Placed',
    submittedOn: '2026-05-16',
    note: 'Closed in eleven days from first submission.',
    feeInr: 560000,
    payoutStatus: 'Paid',
  },
  {
    id: 'sub-3',
    recruiterId: 'rec-1',
    jobId: 'job-8',
    candidateId: 'cand-14',
    status: 'Rejected',
    submittedOn: '2026-09-11',
    note: 'Client wanted higher primary case volume.',
    feeInr: 0,
    payoutStatus: 'Pending',
  },
  {
    id: 'sub-4',
    recruiterId: 'rec-2',
    jobId: 'job-4',
    candidateId: 'cand-7',
    status: 'Client reviewing',
    submittedOn: '2026-09-07',
    note: 'Night-shift preference already confirmed.',
    feeInr: 180000,
    payoutStatus: 'Pending',
  },
  {
    id: 'sub-5',
    recruiterId: 'rec-2',
    jobId: 'job-4',
    candidateId: 'cand-8',
    status: 'Submitted',
    submittedOn: '2026-09-14',
    note: 'Junior for the unit but clears every mandatory requirement.',
    feeInr: 165000,
    payoutStatus: 'Pending',
  },
];

export const seedInvoices: Invoice[] = [
  {
    id: 'inv-1',
    organisationId: 'org-1',
    item: 'Placement fee — Orthopaedic Surgeon',
    amountInr: 560000,
    issuedOn: '2026-06-14',
    status: 'Paid',
  },
  {
    id: 'inv-2',
    organisationId: 'org-1',
    item: 'Talent Pipeline subscription — September',
    amountInr: 7500,
    issuedOn: '2026-09-01',
    status: 'Paid',
  },
  {
    id: 'inv-3',
    organisationId: 'org-2',
    item: 'Talent Pipeline subscription — September',
    amountInr: 7500,
    issuedOn: '2026-09-01',
    status: 'Due',
  },
  {
    id: 'inv-4',
    organisationId: 'org-1',
    item: 'Job boost — Consultant O&G',
    amountInr: 999,
    issuedOn: '2026-08-25',
    status: 'Paid',
  },
  {
    id: 'inv-5',
    organisationId: 'org-6',
    item: 'Talent Pipeline subscription — August',
    amountInr: 7500,
    issuedOn: '2026-08-01',
    status: 'Overdue',
  },
  {
    id: 'inv-6',
    organisationId: 'org-1',
    item: 'Placement fee — Hospital Operations Manager',
    amountInr: 330000,
    issuedOn: '2026-09-08',
    status: 'Due',
  },
];

export const seedPayroll: PayrollEmployee[] = [
  {
    id: 'pay-1',
    name: 'Dr. Harpreet Sandhu',
    organisationId: 'org-1',
    designation: 'Consultant Orthopaedic Surgeon',
    monthlyGrossInr: 395000,
    pepmFeeInr: 499,
    status: 'Active',
  },
  {
    id: 'pay-2',
    name: 'Sister Latha Nair',
    organisationId: 'org-1',
    designation: 'ICU Staff Nurse',
    monthlyGrossInr: 48000,
    pepmFeeInr: 499,
    status: 'Active',
  },
  {
    id: 'pay-3',
    name: 'Ravi Gopalan',
    organisationId: 'org-1',
    designation: 'Hospital Operations Manager',
    monthlyGrossInr: 158000,
    pepmFeeInr: 499,
    status: 'Active',
  },
  {
    id: 'pay-4',
    name: 'Sister Grace Fernandes',
    organisationId: 'org-2',
    designation: 'Neonatal Nurse',
    monthlyGrossInr: 54000,
    pepmFeeInr: 499,
    status: 'On notice',
  },
];

export const seedUsers: PlatformUser[] = [
  {
    id: 'usr-1',
    name: 'Rukmini Desai',
    email: 'rukmini.desai@meridianhealthcity.example',
    role: 'employer',
    organisation: 'Meridian Health City',
    status: 'Active',
    lastActive: '2026-09-19 17:42',
  },
  {
    id: 'usr-2',
    name: 'Dr. Prashant Kale',
    email: 'prashant.kale@sanjeevanimc.example',
    role: 'employer',
    organisation: 'Sanjeevani Mother & Child',
    status: 'Active',
    lastActive: '2026-09-18 11:05',
  },
  {
    id: 'usr-3',
    name: 'Dr. Ananya Rao',
    email: 'ananya.rao@example.in',
    role: 'candidate',
    organisation: '—',
    status: 'Active',
    lastActive: '2026-09-19 09:18',
  },
  {
    id: 'usr-4',
    name: 'Neha Agarwal',
    email: 'neha@caduceussearch.example',
    role: 'recruiter',
    organisation: 'CaduceusSearch Partners',
    status: 'Active',
    lastActive: '2026-09-19 15:30',
  },
  {
    id: 'usr-5',
    name: 'Imtiaz Khan',
    email: 'imtiaz@vitalstaff.example',
    role: 'recruiter',
    organisation: 'VitalStaff Consultancy',
    status: 'Invited',
    lastActive: '—',
  },
  {
    id: 'usr-6',
    name: 'Shreya Nandan',
    email: 'shreya@aarogyadx.example',
    role: 'employer',
    organisation: 'Aarogya Diagnostics',
    status: 'Suspended',
    lastActive: '2026-09-02 08:44',
  },
  {
    id: 'usr-7',
    name: 'Platform Administrator',
    email: 'admin@elixihire.example',
    role: 'admin',
    organisation: 'ElixiHire',
    status: 'Active',
    lastActive: '2026-09-20 08:02',
  },
];

export const seedRiskFlags: RiskFlag[] = [
  {
    id: 'risk-1',
    subject: 'Tarunya Polyclinic Network',
    subjectType: 'Organisation',
    score: 72,
    reasons: [
      'GSTIN prefix does not match the declared state',
      'Three job posts created within four minutes',
      'Contact domain registered 11 days ago',
    ],
    state: 'Open',
    raisedOn: '2026-09-17',
  },
  {
    id: 'risk-2',
    subject: 'Registrar — Emergency Medicine (duplicate)',
    subjectType: 'Job',
    score: 64,
    reasons: [
      '94% description overlap with an existing live post',
      'Same organisation, same location, posted 3 days apart',
    ],
    state: 'Open',
    raisedOn: '2026-09-15',
  },
  {
    id: 'risk-3',
    subject: 'Prabhu Rural Health Mission',
    subjectType: 'Organisation',
    score: 38,
    reasons: ['Not-for-profit CIN with no MSME history', 'First-time poster'],
    state: 'Allowed',
    raisedOn: '2026-09-18',
  },
  {
    id: 'risk-4',
    subject: 'Consultant Cardiologist — ₹90 LPA, no credentials',
    subjectType: 'Job',
    score: 91,
    reasons: [
      'Salary 2.4× the band for this specialty and city',
      'No credential requirements on a consultant post',
      'Organisation unverified',
    ],
    state: 'Blocked',
    raisedOn: '2026-09-12',
  },
];

export const seedInterviews: InterviewSlot[] = [
  {
    id: 'int-1',
    applicationId: 'app-1',
    date: '2026-09-22',
    time: '11:00',
    mode: 'In person',
    state: 'Confirmed',
  },
  {
    id: 'int-2',
    applicationId: 'app-7',
    date: '2026-09-23',
    time: '19:30',
    mode: 'Video call',
    state: 'Invited',
  },
  {
    id: 'int-3',
    applicationId: 'app-17',
    date: '2026-09-24',
    time: '10:00',
    mode: 'In person',
    state: 'Proposed',
  },
];

/**
 * Mock analytics series. Six months of platform history so the Preview analytics
 * screens have something believable to draw. Deterministic, hand-written, not generated.
 */
export const seedTimeToFill = [
  { month: 'Apr', days: 41, placements: 3 },
  { month: 'May', days: 38, placements: 5 },
  { month: 'Jun', days: 34, placements: 6 },
  { month: 'Jul', days: 31, placements: 4 },
  { month: 'Aug', days: 27, placements: 7 },
  { month: 'Sep', days: 24, placements: 9 },
];

export const seedSupplyDemand = [
  { specialty: 'Obstetrics & Gynaecology', openRoles: 4, availableCandidates: 3 },
  { specialty: 'Critical Care', openRoles: 6, availableCandidates: 9 },
  { specialty: 'Paediatrics / Neonatology', openRoles: 3, availableCandidates: 4 },
  { specialty: 'Radiology', openRoles: 3, availableCandidates: 5 },
  { specialty: 'Cardiology', openRoles: 2, availableCandidates: 2 },
  { specialty: 'Anaesthesia', openRoles: 3, availableCandidates: 2 },
  { specialty: 'Oncology', openRoles: 2, availableCandidates: 2 },
  { specialty: 'Physiotherapy', openRoles: 2, availableCandidates: 3 },
];

export const seedSourceMix = [
  { source: 'Direct application', value: 42 },
  { source: 'Employer sourcing', value: 23 },
  { source: 'Recruiter submission', value: 19 },
  { source: 'Referral', value: 11 },
  { source: 'Job boost', value: 5 },
];

export const seedRetention = [
  { month: 'Apr', at90Days: 88 },
  { month: 'May', at90Days: 90 },
  { month: 'Jun', at90Days: 89 },
  { month: 'Jul', at90Days: 92 },
  { month: 'Aug', at90Days: 93 },
  { month: 'Sep', at90Days: 94 },
];

/**
 * The starting taxonomy, seeded from the static reference lists.
 *
 * Once in the store it becomes editable data — the Admin taxonomy manager writes to it
 * and every dropdown in the app reads from it, which is the "extend without rework" proof.
 */
export const seedTaxonomy: Taxonomy = {
  roleTypes: [...ROLE_TYPES],
  specialties: [...SPECIALTIES],
  subSpecialties: Object.fromEntries(
    Object.entries(SUB_SPECIALTIES).map(([key, value]) => [key, [...value]]),
  ),
  credentials: [...CREDENTIALS],
  shifts: [...SHIFTS],
  employmentTypes: [...EMPLOYMENT_TYPES],
  locations: [...LOCATIONS],
};

/** A fresh, deep copy of the seed. Used on first load and by "Reset demo". */
export function createSeedState(): DemoState {
  return JSON.parse(
    JSON.stringify({
      organisations: seedOrganisations,
      jobs: seedJobs,
      candidates: seedCandidates,
      applications: seedApplications,
      audit: seedAudit,
      activeEmployerOrgId: 'org-1',
      activeCandidateId: 'cand-1',
      activeRecruiterId: 'rec-1',
      taxonomy: seedTaxonomy,
      recruiters: seedRecruiters,
      submissions: seedSubmissions,
      invoices: seedInvoices,
      payroll: seedPayroll,
      users: seedUsers,
      riskFlags: seedRiskFlags,
      interviews: seedInterviews,
      savedSearches: [
        {
          id: 'search-1',
          name: 'Evening O&G in Bengaluru',
          createdOn: '2026-09-12',
          filters: { Specialty: 'Obstetrics & Gynaecology', Location: 'Bengaluru, KA' },
        },
      ],
      jobAlertsOn: true,
    }),
  ) as DemoState;
}
